### ISSUE TITLE
Creación de clase usuario

### ISSUE THREAD

**Issue by PabloSoligo2014** [PabloSoligo2014/T10#1]
Atento a las consultas que Diego Oña me enviara por correo electrónico realizo la siguientes aclaraciones.

La clase login no esta creada, deben crearla ustedes (Grupo 02), codificarla. Ponerla en la carpeta model y subirla al github cuando este finalizada.

Propiedad login: es el login del usuario, unico e irrepetible, (No es un metodo para loguearse ni nada parecido) podemos tener mas de un usuario Juan Perez, pero los login deben ser distintos, uno se pondra jperez el otro se conformara con juanperez para dar un ejemplo

Propiedad Nombre: Aca si pueden existir dos Juan Perez, es descriptivo y no tiene relevancia a nivel sistema.

Limites de caracteres de los campos:
Login:20
Password:20
Nombre:128

Slds

**Comment by MicaLucas** [comment]
Hola, nuestro grupo ya hizo la clase usuario con login, password y nombre, pero no sabemos como hacer la parte de la encriptacion. Estuvimos viendo algunas formas pero no entendemos muy bien como funciona. Gracias. Lucas Quinteiro.

**Comment by PabloSoligo2014** [comment]
Prueben este método de encripcion simétrica. Lo desarrolle yo rápidamente, es para evitar hacer uso de las clases de .net que llevaría mas tiempo explicar y todavía no se han visto muchos temas.
Clave interna es la palabra secreta de encripcion. Me hacen acordar que les explique porque este método de encripcion es inseguro.
Por favor probar!!!


    private string SimEncrypt(string originalString)
    {

        StringBuilder inSb = new StringBuilder(originalString);
        StringBuilder outSb = new StringBuilder(originalString.Length);

        char c;

        for (int i = 0; i < originalString.Length; i++)
        {
            c = inSb[i];
            c = (char)(c ^ (char)ClaveInterna[(i+4)%4]);
            outSb.Append(c);

        }

        return outSb.ToString();

    }

**Comment by PabloSoligo2014** [comment]
Dos comentarios, 
1.Se deduce del código que la palabra secreta tiene que tener al menos 4 caracteres y también la password.
2.No tengan miedo de subir el código intermedio aunque no este terminado. Esta vez el corte lo hacemos el sábado.

**Comment by diegoonia** [comment]
Profesor yo ya hice el commit hace una hora, pero no se porque no lo ven los demás, yo lo veo como que se hizo. Está hecha la clase usuario pero sin el encriptado.

![commit](https://cloud.githubusercontent.com/assets/11900592/7243473/eb0ced6c-e7a3-11e4-9726-d52293dddf9b.png)

**Comment by PabloSoligo2014** [comment]
Como lo subiste? Con GIT for Windows?

**Comment by diegoonia** [comment]
Sisi, lo hice con el de windows, me decía "commit to master" o algo así, se lleno una barra como que todo estaba bien, y me aparece ahí y aca en la web como que está realizado.
Ahora voy a poner revertir y lo voy a subir devuelta a ver si se hace bien.

**Comment by diegoonia** [comment]
Lo hice así, no se si me falta algún paso o lo estoy haciendo mal.

![github](https://cloud.githubusercontent.com/assets/11900592/7262034/ba6bba36-e84c-11e4-8e80-c197f4000607.png)

**Comment by PabloSoligo2014** [comment]
Ok lo veo. Dejame investigar a ver si hay algun problema de permisos

**Comment by PabloSoligo2014** [comment]
Ya esta genere el pull request y luego merge (Aplique los cambios), no se si tu usuario te permite hacerlo. Lo vemos. Me diste el pie perfecto para comentar algunos temas el sabado. Fijate que deje el script de encripcion en el issue este, aplicalo y saca los console.WriteLine(), estan mal y el sabado les explico porque.....

**Comment by MicaLucas** [comment]
Hola profe, quería preguntarle acerca de lo que nos pidió del usuario. Para que no se repita no tendría que haber una base de datos previamente cargada con todos los nombres de usuario y así poder compararlos? Gracias, De Rito Micaela

**Comment by PabloSoligo2014** [comment]
Si, ahora no podes impedir que se creen dos usuarios con el mismo login.Vamos a llegar a eso a medida que avanzamos, cuando trabajemos con base de datos vamos a tener mas herramientas para esto.

**Comment by PabloSoligo2014** [comment]
Recien vi el codigo, me parece que tienen la condicion mal. Si la cadena es mayor que 20 trunco, sino queda como esta, se me hace que lo hicieron al revés.
Agregaron el codigo de encripcion pero no lo usan. La password se guardar internamente en la clase de manera encriptada.
