### ISSUE TITLE
Clase Seleccion

### ISSUE THREAD

**Issue by PabloSoligo2014** [PabloSoligo2014/T10#3]
Atributos

idSeleccion de tipo integer.
Descripcion de tipo string, proteger para que no supere los 255 caracteres.

La clase debe ir dentro de la carpeta model, verificar que funcione correctamente la solucion antes de subir

**Comment by DanielaPalotti** [comment]
BUENAS TARDES.... PROFE ACÁ ESTÁ LO QUE HICIMOS, LO QUE NO ENTENDEMOS ES CÓMO SUBIRLO. OTRO INCONVENIENTE ES QUE HICIMOS EL MAIN PARA PROBARLO PERO NO PUDIMOS HACERLO FUNCIONAR; TAMPOCO ENTENDEMOS EN QUÉ FALLAMOS. 


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ConsoleApplication1
{
    class Seleccion
    {
        private string descripcion;

        public void SetDescripcion(string value)
        {
            if (value.Length >= 256)
            {
                descripcion = value.Substring(0, 256);
            }
            else
            {
                descripcion = value;
            }
        }
            public string GetDescripcion(){
                return descripcion;}

            private int idSeleccion;

            public int IDseleccion
            {
                get { return idSeleccion; }
                set { idSeleccion = value; }
            }


    }
}
