### ISSUE TITLE
Encuesta y Pregunta

### ISSUE THREAD

**Issue by PabloSoligo2014** [PabloSoligo2014/T10#5]
Para el alumno/alumna que me consulto hoy por los atributos de las clases Encuesta y respuesta adjunto una imagen que contiene los atributos y los valores maximos de caracteres para las cadenas
![encuestaypregunta](https://cloud.githubusercontent.com/assets/8715226/7556810/e125d878-f756-11e4-98f6-13a88ec91986.png)

Slds

**Comment by FirpoTorres** [comment]
Profe, podría mandar todo? Así podemos ver como sería la base de datos para tenerla preparada para la clase que viene. Saludos.
